const listenerTypes = {
  SERVER_ERROR: 'SERVER_ERROR',
  SERVER_TIMER: 'SERVER_TIMER',
  SERVER_USERS_ERROR: 'SERVER_USERS_ERROR',
  SERVER_USERS: 'SERVER_USERS',
  SERER_STOCK: 'SERVER_STOCK',
  SERVER_STOCK_ERROR: 'SERVER_STOCK_ERROR'
}

export default listenerTypes
